### ISSUE TITLE
화면 프로토타입 생성

### ISSUE THREAD

**Issue by ued123** [ued123/modeling#10]
화면 프로토타입 구성하기.

**Comment by ued123** [comment]
### 자판기 화면 프로토타입
https://ovenapp.io/project/cRMcJvhH7BRhYEFYFMJPHsvk5ycYL8KM#puZGu

**Comment by ued123** [comment]
자판기 화면 프로토타입 version 2 
https://ovenapp.io/project/cRMcJvhH7BRhYEFYFMJPHsvk5ycYL8KM#duqMe

**Comment by ued123** [comment]
관리자 페이지 고민좀 해봐야할듯

**Comment by sangholim** [comment]
@ued123 
코멘트 남기신 프로토 타입 링크 보고, 간단하게 프로토 타입 만들어 봤는데 확인 부탁드릴게요. 🙏 
![image](https://user-images.githubusercontent.com/55565835/172967697-6ee4b459-e42d-4e16-91d2-7b3b89148c73.png)

**Comment by ued123** [comment]
## 상품 진열
### 정책
-  동일한 상품도 여러개 진열이 가능하다.
- 서버에서는 진열할수 있는 상품 리스트를 클라이언트에게 리스트로 전달한다.
- 상품이 없는 경우 품절로 표시한다.

<details>
<summary>진열할 상품 정보를 불러온다. </summary>

> - url : /drinks/display
> - methods : GET
> - Content-type : application/json

```jsonc
Response Code: 200
Response body:
[...,
  {
     "position" : 1,
     "status" : AVAILABLE | SOLD_OUT,
     "drinkName" : 콜라,
     "price" : 3000,
  }
]
```
</details>

상품 리스트를 queueId에 따라 매핑해서 넣어준다.
품절 여부는 프론트 상에서만 queue id 에 해당하는 음료수 데이터가 없을때, 품절로 표시함.
