### ISSUE TITLE
정의하지 않은 예외 발생시 에러 처리

### ISSUE THREAD

**Issue by sangholim** [ued123/modeling#101]
## 요약
- `ExceptionTranslator ` 에서 정의하지 않은 예외 발생한 경우, 에러 응답 생성 로직 작업 요청 드립니다.
- `CashControllerTest.kt` 내에 테스트 케이스 추가 요청 드립니다.
### 에러 응답 정의
- status: 500 Inster Server Error
- body: 
```jsonc
{
    "timestamp": 1667457059982,
    "status": 500,
    "error": "Internal Server Error
}
```

**Comment by ued123** [comment]
@sangholim 
테스트 케이스에서 임의로 500 error를 어떻게 발생시켜야할지 모르겠네요

**Comment by ued123** [comment]
amount에 엄청 큰 값을 넣어서 오버플로우를 발생시키면 가능할거같네요. 이렇게 한번 해보겠습니다

**Comment by sangholim** [comment]
@ued123 
- 아래 형태로 에러 정의 요청 드립니다.. 작업 번복하게 해서 죄성합니다.. 🙏 
```jsonc
{
    "timestamp": 1667457059982,
    "code": 500,
    "message": "Internal Server Error
}

```

**Comment by ued123** [comment]
괜찮습니다. 그렇게 한번 바꿔보겠습니다
