### ISSUE TITLE
cash 거스름돈 api

### ISSUE THREAD

**Issue by ued123** [ued123/modeling#106]
## 거스름돈 요구사항
1. 자판기에서 거스름돈 버튼 클릭시 거스름돈 반환.

## 구현 시나리오
1.  자판기 요청시 지갑(cash) 데이터에서 남은 잔액 데이터를 가져온다.
2. 잔액 데이터가 0원 일때 에러 응답 반환한다.(잔액이 없습니다)
3. 지갑의 변경된 내용을 저장한다.
4. 거스름돈 이력을 거래이력에 남긴다.
5. 거스름돈을 반환. 

### 기능
- 거스름돈을 반환 한다. 
### Schema
```http
url: /cash/change
methods: PUT
content-type: application/json
```

### Response
```http
code: 200
```

```jsonc
{
      "amount":  거스름돈 반환 금액
}
```
```http
code: 404
```
```jsonc
{
 "timeStamp": "발생시간",
 "message": "잔액이 없습니다."
}
```

**Comment by ued123** [comment]
transaction Type 추가 필요함

**Comment by ued123** [comment]
@sangholim
잔액이 0원일때 cashService쪽에서 404 에러를 발생시켜야 할텐데
404 NotFound에 대해서 따로 커스텀 에러 클래스를 만들어야 할까요?
기존에 404가 존재하는 exception인 `HttpServerErrorException` 이나 `HttpClientErrorException` 같은 경우는 클라이언트 <-> 서버간 에러이기 때문에 적합하지 않은 것 같아서요.

**Comment by sangholim** [comment]
@sangholim 
- 캐쉬가 없는 경우 예외 클래스 작성이 필요합니다.
  `ResponseStatusException` 상속 받아서 처리 하시면 될거 같습니다.

**Comment by ued123** [comment]
@sangholim 
거스름돈 시나리오를 좀 바꿔야 할거 같아요.
금액 입금과 거스름돈 로직 순서를 맞추려고 합니다.

### 현재 금액 입금(deposit) api 순서
- 이력을 저장하고 -> cash를 상태 저장

### AS-IS(현재) 거스름돈 시나리오
- cash 상태 저장 후 -> 이력을 저장

### TO-BE(변경후) 거스름돈 시나리오
- 이력을 저장 -> cash 상태 저장

**Comment by ued123** [comment]
넵 그러면 deposit을 수정하도록 하겠습니다
