### ISSUE TITLE
주문하기 (상품구매)

### ISSUE THREAD

**Issue by ued123** [ued123/modeling#107]
## 1차 음료수 구매 시나리오
1.  사용자는 음료수를 선택하고 구매를 요청
2. 선택한 음료수의 수량이 존재하는지 확인한다. (수량이 없으면 리턴)
3. 음료수 정보를 가져온다.
4. 지갑의 잔액을 확인 한 후 음료수 가격 정보와 비교한다. (음료수 금액 만큼의 잔액이 없으면 리턴)
5. 음료수의 가격 만큼 지갑 에서 차감한다.
6. 구매한 음료수 정보를 바탕으로 주문서 생성
7. 구매 이력을 생성한다.

**Comment by ued123** [comment]
## 1차 음료수 구매 시나리오
1.  사용자는 음료수를 선택하고 구매를 요청
2. 선택한 음료수의 수량이 존재하는지 확인한다. (수량이 없으면 리턴)
3. 음료수 정보를 가져온다.
4. 지갑의 잔액을 확인 한 후 음료수 가격 정보와 비교한다. (음료수 금액 만큼의 잔액이 없으면 리턴)
5. 음료수의 가격 만큼 지갑 에서 차감한다.
6. 구매한 음료수 정보를 바탕으로 주문서 생성
7. 구매 이력을 생성한다.

**Comment by sangholim** [comment]
## Task
- [ ] 구매 프로젝트 생성
- [ ] entitymapper
- [ ] 구매 API 정의서

**Comment by sangholim** [comment]
## 요약
- project: purchase-api
### API
- url: /purchases/drink
- method : POST
- content-type: application-json
#### Request
- body
```jsonc
{
  "drinkCode": "음료 물류 코드",
  "amount": "입금한 금액"
}
```
#### Response
- code: 200
- body
```jsonc
{
  "amount": "입금한 금액"
}
```


### 시나리오
-

**Comment by sangholim** [comment]
@ued123 
- 시나리오 변경이 필요할것 같습니다.
- [drink] 음료수 가져오기
  - 음료수가 없는 경우 에러
  - 수량이 부족한 경우 에러
- [cash] 보유 금액으로 부터 음료수 금액을 차감한다

**Comment by ued123** [comment]
아 넵 알겠습니다

**Comment by ued123** [comment]
@sangholim 
음료수가 없는 경우 에러와 수량이 부족한 경우 에러에 대해서 구현 중간에 질문드립니다.
-> 음료수가 없을때와 수량이 부족한 경우에 대한 커스텀 exception을 제가 정의 하고 핸들링 하면 될까요?

**Comment by sangholim** [comment]
@ued123 
아래의 에러 케이스를 정의해 보세요
- 음료수 없는 경우
- 음료수 수량이 부족한 경우

**Comment by ued123** [comment]
@sangholim 

cash & order 서비스 도메인 결합시에
-  [cash] 보유 금액으로 부터 음료수 금액을 차감한다
-  [order] 주문서 작성

어제 얘기하셨는지 가물가물한데. cash의 charge 기능에 리턴값이 없다보니. order 도메인에서 주문서를 생성하기 전에 cash 도메인에서 정상적으로 차감이 수행 되었는지 알 방법이 없는거 같습니다. 그래서 순차적으로 결합되는 느낌이 아닌거 같아서요.
```java
    public void charge(Long amount)
```

그래서 결론은 cash charge에 cash 리턴값을 주는게 좋을거 같은데 어떻게 생각하시는지요?

**Comment by sangholim** [comment]
@ued123 
- 두가지 방법으로 말씀했던거 같습니다
  - charge가 정상 처리되고 return 값이 없는 경우, 해당 주문서의 금액은 음료수 금액으로 처리
  - charge가 정상 처리되고 거래 내역을 반환하는 경우, 해당 주문서의 금액은 거래 내역의 금액값을 사용

**Comment by ued123** [comment]
넵 그래서 저도 거래내역을 반환해서 주문서 작성시 금액을 참조하는게 좀 더 명확하지 않을까 해서요
저번에 말하셨던것 처럼 해당 금액에 대한 입증을 구매 이력으로 해줄수 있으니깐요.
또 리턴값이 있는게 나중에 단위테스트에도 도움이 될거 같기도 하고요.
그래서 제생각은 두번쨰 방법이 좋지 않나 생각됩니다.

**Comment by sangholim** [comment]
@ued123 
- 네네 그럼 거래 내역을 반환하시고 진행하실 될듯합니다
