### ISSUE TITLE
음료 전시, 음료 도메인 개선

### ISSUE THREAD

**Issue by sangholim** [ued123/modeling#120]
## 요약
- 구매하기 시나리오전 `음료 전시` `음료` 도메인 검토 필요함
### 음료 전시 개선
- 상품 코드 필요
- 음료 전시에 연결된 음료가 없는경우, status SOLD_OUT으로 수정
### 음료 개선
- `List<Display> displays;` 불필요
- 상품 관리 코드가 필요: 물류쪽에서 들어오는 상품을 관리하는 코드
  - 코카 콜라 500ml  - xx-1234
  - 코카 콜라 250ml  - xx-1233

**Comment by ued123** [comment]
음료 전시에 연결된 음료가 없는경우, status SOLD_OUT으로 수정
-> 이부분은 상품진열 api 응답시에 음료 전시에 연결이 안되있어도 상품 전체 리스트를 보여주라는 말씀이신거죠?

상품 관리 코드가 필요: 물류쪽에서 들어오는 상품을 관리하는 코드
-> 음료수에 대한 상품 코드 필드를 추가해서 관리를 해야 할까요? 이건 내일 얘기해봐야 할거 같네요.

**Comment by sangholim** [comment]
@ued123 
###  `음료 전시에 연결된 음료가 없는경우, status SOLD_OUT으로 수정`
- PR 작업후 공유 드리겠습니다.
### `상품 관리 코드가 필요: 물류쪽에서 들어오는 상품을 관리하는 코드`
- 물류에서 관리되는 코드가 중복되지 않는경우, 상품을 등록할수 있습니다.
   이 뜻은 mongodb 의 ObjectId 보다 상품 물류 관리코드에 의존해야 합니다.
   만약 등록된 상품 물류 코드가 변경된 경우, 실제로 다른 상품으로 교체가 되는겁니다.
   현재 전시에서는 상품 번호 `ObjectId`로 매핑되서 전시 결과에는 문제 없어 보이지만
   이렇게 되면 전시 상품을 관리하는 의미가 없어집니다.
