### ISSUE TITLE
drink&display 도메인 entitymapper 적용

### ISSUE THREAD

**Issue by ued123** [ued123/modeling#143]

**Comment by ued123** [comment]
@sangholim 

 - display 도메인이 mapper로 바꾸기엔 로직이 어렵네요. 
 - toDisplayDrinkResult 메서드는 매핑이라기보다 필터링에 가까운거 같습니다. 이걸 엔티티매퍼에서 처리할 수 있을지 모르겠습니다. 그래서 이 메서드를 entity 안에서 그대로 사용하고 DisplayDrinkView로 변환하기위해 displaymapper를 entity안에다 넣어서 처리하기엔 너무 억지 같아서요

```java
public class Display {

    /**
     * 전시 등록된 음료수 리스트
     */
    @ReadOnlyProperty
    List<Drink> drinks;

..... 

    /**
     * 전시 음료결과 데이터 변환
     */
    public DisplayDrinkView toDisplayDrinkResult() {
        return drinks.stream().filter(Objects::nonNull).findFirst().map(this::toDisplayDrinkView).orElse(null);
    }

    /**
     * DisplayDrinkView 변환 함수
     *
     * @param drink 음료수
     */
    private DisplayDrinkView toDisplayDrinkView(Drink drink) {
        Status status = (drink.quantity == 0) ? Status.SOLDOUT : Status.AVAILABLE;
        return new DisplayDrinkView(drink.code, position, status, drink.name, drink.price);
    }

```

**Comment by sangholim** [comment]
@ued123 
- 시간 되시면 작업 브렌치 푸시해주세용

**Comment by ued123** [comment]
> @ued123
> 
> * 시간 되시면 작업 브렌치 푸시해주세용

제 생각에 view 반환시 아래의 느낌으로 짜야할거 같아서 mapper만을 구현한상태로 두었고 .. 적용을 고민하고 있습니다.
[drink-api/src/main/java/com/example/mongo/model/entitymapper/DisplayDrinkMapper.java](https://github.com/ued123/modeling/commit/95acc610021d0910bed9a6116d5bc648bfa4a6d0#diff-78af7beff08ba104d5c33a2e849dfa909198dbdbeb852399fc93d88014ee44b5)
