### ISSUE TITLE
[drink] 음료수 가져오기 서비스 구현

### ISSUE THREAD

**Issue by ued123** [ued123/modeling#148]
@ued123 
- 시나리오 변경이 필요할것 같습니다.
- [drink] 음료수 가져오기 (가져올때 수량 -1)
  - 음료수가 없는 경우 에러
  - 수량이 부족한 경우 에러
 
_Originally posted by @sangholim in https://github.com/ued123/modeling/issues/107#issuecomment-1346521639_

**Comment by ued123** [comment]
> ### API
> - url: /purchases/drink
> - method : POST
> - content-type: application-json
> #### Request
> - body
> ```jsonc
> {
>  "drinkCode": "음료 물류 코드"
> }
> ```
> #### Response
> - code: 204 No Content


## 에러케이스

- 음료수코드에 대한 음료수 정보가 존재하지 않을떄

```http
code: 404
```
```jsonc
{
 "timeStamp": "발생시간",
 "message": "음료수가 존재하지 않습니다."
}
```
- 음료수 수량이 부족한 경우 
  - 음료수 수량이 바닥났을때 에러코드가 애매하네요. 404라고 보내도 될지... 

```http
code: 404
```
```jsonc
{
 "timeStamp": "발생시간",
 "message": "해당 제품은 품절입니다."
}
```

**Comment by sangholim** [comment]
@ued123 
- 음료수 부족한 경우, code: 400 으로 해주심 될듯요

**Comment by ued123** [comment]
404 -> 400 수정완료
