### ISSUE TITLE
api 응답값 이슈 - ObjectId

### ISSUE THREAD

**Issue by sangholim** [ued123/modeling#17]
### 요약
- api 응답값 클래스가 ObjectId 인 경우, 아래의 데이터 형태로 반환됨
```jsonc
 "id": {
   "timestamp": xxx,
   "date": yyyy
}
```
### 조치 - 가이드
- jackson-object-mapper에서 특정 클래스를 직렬화 할수 있게 일괄 설정이 가능
- [참고](https://stackoverflow.com/questions/9065042/java-spring-mappingjacksonjsonview-not-doing-tostring-on-mongodb-objectid)
```java
@Bean
public Jackson2ObjectMapperBuilderCustomizer jsonCustomizer() {
    return builder -> builder.serializerByType(ObjectId.class, ToStringSerializer.instance);
}
```
@ued123 
- 조치시기는 현재 작업 이후 또는 작업중에 정하면 좋을것 같습니다.

**Comment by ued123** [comment]
@sangholim 
아 감사합니다. 참고하도록 하겠습니다
