### ISSUE TITLE
openapi 연동하기

### ISSUE THREAD

**Issue by sangholim** [ued123/modeling#39]
- spring openapi doc 를 이용하여 연동
- https://springdoc.org
- https://dash.readme.com/
- https://github.com/springdoc/springdoc-openapi-gradle-plugin

**Comment by ued123** [comment]
@sangholim 
generateOpenApiDocs 명령어를 통해서 openapi.json 파일까지 뽑아내는데 성공했지만
해당 명령어가 springboot를 실행해서 작동하기 때문에 mockmvc 때 이슈와 마찬가지로 application 모듈쪽에 openapi 관련된 설정이 위치하게 되었습니다. 
![image](https://user-images.githubusercontent.com/32861341/182300489-63e521b7-343b-412a-9302-de175919647d.png)
![image](https://user-images.githubusercontent.com/32861341/182300939-393b8b45-fd6b-4f38-95f2-80e5305ec6a1.png)
![image](https://user-images.githubusercontent.com/32861341/182300513-055d1c1e-e1b6-4655-a048-e7e1fa6f6f85.png)

제 생각은 모노리스 방식이기 때문에 결과적으로는 모듈이 합쳐져서 결과가 나오는데는 문제는 없었고
generateOpenApiDocs 명령어를 실행할때 결국엔 **프로젝트 상단 경로에서 gradlew 를 통해 실행**하기 때문에 이대로 진행해도 상관 없을거 같습니다.

이대로 진행할까요?
