### ISSUE TITLE
음료수 구매 하기 시나리오 작성

### ISSUE THREAD

**Issue by sangholim** [ued123/modeling#40]
### 요약
- 이커머스 처럼 유저별로 구매를 보장하는 시나리오는 차후에 진행
- 순수 자판기에서 처리하는 방식을 준수해서 API 만들고자 한다.
- 입금/ 거스름돈 반환은 하나의 도메인에서 관리할수 있다. `cash`
- 입금/ 거스름돈 반환/음료 구매시  거래 도메인 필요하다. `transaction`

### 필요 기능
- [ ] 입금하기
- [ ] 단일 상품 구매
- [ ] 거스름돈 반환

**Comment by sangholim** [comment]
### 거래
- 잔액, 상품 구매에 대한 내용을 관리하는 도메인은 `transaction`
- 캐시 데이터는 배열 값으로 저장된다.
- 상품 데이터는 단일 값으로 저장된다.
- 거래에 대한 필드 정의
```jsonc
{
  "거래번호",
  "구분" :"음료 구매" | "캐쉬 입금" | "캐쉬 거스름돈",
  "음료": {
    "음료번호",
    "음료명",
    "전시명",
    "금액"
  },
  "캐시": [
    ...,
    {
      "캐시번호",
      "총계",
      "잔액"
    }
  ],
  "생성일"
}

```

### 거래 시나리오
- 입금 했을때, 거래 데이터
  - 잔액 데이터는 존재해야한다.
  - 음료 데이터는 없어야 한다.

- 거스름돈, 거래 데이터
  - 잔액 데이터는 존재해야 한다.
  - 음료 데이터는 없어야 한다.

- 음료 구매
  - 음료 데이터는 존재해야 한다.
  - 잔액 데이터는 존재해야 한다.

**Comment by ued123** [comment]
## 음료수 거래 시나리오
한번 이전에 보여주신 장애 대응을 위한 이력 관리를 초점으로 두어서 짜봤습니다.

### 금액 입금

1. 사용자는 금액을 자판기에 투입한다.
2. 1원 이상 입금시에 거래가 시작된다. 
4. 입금한 금액에 대한 입금 이력이 저장된다.

### 음료수 구매

1. 사용자는 원하는 음료수의 구매 버튼을 클릭한다.
2. 선택한 음료수에 가격을 불러온다.
4. 최근 입금 이력에 캐시를 불러온다.
5. 캐시와 음료수 가격을 비교하여 구매 한다.
6. 음료수를 구입한 구매 이력과 잔액 이력이 저장 된다.

### 거스름돈 반환

1. 사용자는 거스름돈 반환 버튼을 누른다.
2. 최근 생성된 거래이력의 잔액 데이터를 확인한다.
3. 잔액 데이터가 1이상일 경우 거스름돈을 반환 이력을 저장한다.
5. 사용자에게 거스름돈을 반환한다.
6. 거래 종료

### 장애 대응
- 사용자의 관리 정보가 없으므로 거래 시간(이력 생성일)을 토대로 이력을 확인 (문제가 발생한 시간을 알아 내야함)
