### ISSUE TITLE
입금하기 API 정의서

### ISSUE THREAD

**Issue by sangholim** [ued123/modeling#41]
## 요약
- 고객이 자판기에 금액을 투입시 필요한 API 정의서가 필요합니다.
- #46 내용을 고려해서 API 정의서 작성 요청드립니다.

**Comment by ued123** [comment]
## 금액 투입
### 정책
- 자판기에 금액을 투입한다.
- 금액 투입 시점의 시간이 들어간다.

> - url : /cashs/put
> - methods : POST
> - Content-type : application/json

|필드|유형|설명|
|------|---|---|
|cash|정수형|1회 투입한 금액|
|category|문자열|구분|

### sample request
```jsonc
{
      "cash": 500,
      "category": "deposit"
}
```

### sample response
```jsonc
{
      "responseCode": 200,
      "desc" : 금액 투입 성공
}
```

**Comment by sangholim** [comment]
## 금액 투입
- 제가 생각한 초안인데 고민해보시고 결정하십 될것 같습니다.
### Schema
```http
url: /cash/deposit
methods: PUT
content-type: application/json
```
### Request
```jsonc
{
      "amount": "투입 금액"
}
```
### Response
```http
code: 200
status: created
```

```jsonc
{
      "balance": "남은 금액"
}
```
