### ISSUE TITLE
음료수 구매하기 도메인 개선

### ISSUE THREAD

**Issue by ued123** [ued123/modeling#46]
## 요약
- #40  issue 재정리
### project: cash-api
- 자판기 음료수 구매할수 있는 금액을 관리할수 있는 도메인: cash
- 자판기  `입금/출금`시 거래 내역  관리할수 있는 도메인: transaction
### project: purchase-api
- cash, transaction, drink 로직을 참조해서 사용할수 있습니다
- 주문: purchase

**Comment by ued123** [comment]
입금하기 api 구현

**Comment by ued123** [comment]
## 구조
저번주에 말한것처럼 cash 라는 도메인을 가져가는게 좋을거 같고 그래서 캐시쪽에서 **잔액을** 가지고 있도록 만들까 합니다.

제 나름대로 도메인에 쓰일 json 데이터 구조를 만들어보고 있는데 구분이 없으면..
총 판매금액 같은 통계를 집계 할 수가 없을거 같아서 생각이 필요한거 같아요.

### transaction

```jsonc
{
  "거래번호",
  "구분" : "입금" | "거스름돈" | "음료수 거래",
  "캐시": "금액"
  "생성일"
}
```

총 판매 금액 : 음료수 거래가 구분인 이력을 모두 더한 값

### cash
```jsonc
{
   "잔액" : "금액"
}

```

**Comment by sangholim** [comment]
@ued123 
## transaction
### 도메인 역할
- 입금, 출금을 중심으로 금액의 내역을 관리합니다.
   그에 대한 설명이 필요한 경우 `note` 같은 필드에서 처리하는게 좋을것 같습니다.
- 판매 금액은 상품을 정보를 포함하기 떄문에 주문서에서 처리하는게 맞는거 같습니다.
### 입금/출금에 따른 예제
- 입금
  - 금액 투입
- 출금
  - 거스름돈 반환
  - 음료수 구매
