### ISSUE TITLE
테스트 프레임워크 검토 - spock

### ISSUE THREAD

**Issue by sangholim** [ued123/modeling#52]
### ~~Junit~~
- 간단한 결과를 반환하는 단위 테스트에서는 사용하기 편함
- 기능이 복잡한 경우, 테스트 케이스가 많아지면 상당한 작업시간이 소요된다
- 테스트 케이스가 많아지면 명세를 하는데 상당한 고민을 할수가 있다.
### ~~Cucumber~~
- BDD 기반 프레임워크고 통합 테스트에서 많이 사용한다. 현 프로젝트는 단위 테스트 기반이기 떄문에 어울리지 않는다.
- BDD 조건의 시나리오 파일을 관리해야하고, 파일에 설정과 테스트 클래스 매핑하는 작업이 필요하기 떄문에 시간 소모가 크다.
### Spock
- BDD 기반 프레임워크
- 단위 테스트 내에서도 BDD 시나리오를 작성할수 있기 떄문에, 관리가 수월하다.

**Comment by ued123** [comment]
공부하다가 mockito에서 제공하는 bdd api 라는 것도 있는거 같은데 이건 별로인가요?

**Comment by sangholim** [comment]
@ued123 
- bdd-mockito 는 단위 테스트 내에서 given when then을 함수형으로 호출할수 있지만, 단점이 어떤한 케이스에 사용했는지
  명세를 할수 없는게 단점입니다.
- 반면  spock는 bdd 내에서도 명세 기반으로 given when then을 사용할수 있는게 장점입니다,  그리고 spock 도입이 되면, 기존 테스트 라이브러리는 제거 예정입니다.

**Comment by sangholim** [comment]
## 테스트 케이스 명세
### Spock
![image](https://user-images.githubusercontent.com/55565835/191022676-4afc1afe-7e47-4f4e-a86a-868a27667b53.png)
### Bdd-Mockito
![image](https://user-images.githubusercontent.com/55565835/191022810-14090543-e704-4169-a7c2-0d5f185b8ac1.png)
