### ISSUE TITLE
금액 투입 api 구현

### ISSUE THREAD

**Issue by ued123** [ued123/modeling#53]
제가 짠거보다 깔끔한거 같아 sangholim 설계론으로 결정

### Schema
```http
url: /cash/deposit
methods: PUT
content-type: application/json
```
### Request
```jsonc
{
      "amount": 투입 금액
}
```
### Response
```http
code: 200
status: created
```

```jsonc
{
      "balance": 남은 금액
}
```

_Originally posted by @sangholim in https://github.com/ued123/modeling/issues/41#issuecomment-1250001544_

**Comment by ued123** [comment]
## tasks
- [x] cashRepository 구현 
- [x] bdd repository 테스트

**Comment by sangholim** [comment]
@ued123 
- 요청필드 `amount` 가 금액이 0 이하인 경우 예외처리가 필요합니다.
- javax.validation을 활용해 주세요

**Comment by ued123** [comment]
예시 `@PositiveOrzero` 같은 부분
