### ISSUE TITLE
spock식 stub을 정의할때 @MockBean 이슈

### ISSUE THREAD

**Issue by ued123** [ued123/modeling#68]
## 이슈
- spock 방식으로 stub을 정의할때 아래와 같이 정의를 할 수 있는데
```groovy
cashService = Stub();
cashService.deposit(new CashDepositPayLoad(1000L)) >> new CashDepositView(1000L);
```

- 아래처럼 stub시에 @Mockbean으로 정의 되어 있으면 에러가 발생한다.

```groovy
@MockBean
private CashService cashService = Stub();
```

- 에러로그
```
Could not inject field: private com.example.cash.service.CashService com.example.cash.controller.CashControllerTest.cashService; nested exception is java.lang.IllegalStateException:
```
## 조치
해결방법은 두가지
1. @MockBean 대신하여 @SpringBean을 사용하면 해결
2. @MockBean을 사용하고 기존의 mockito when방식으로 stub해도 해결

## 참고
- spock는 @SpringBean을 사용하는것을 권장한다고 함
[https://stackoverflow.com/questions/55020459/is-there-a-way-to-use-mockbean-annotation-while-working-with-spock-framework](url)

**Comment by sangholim** [comment]
@ued123 
- 참고로 mocking 기반으로 테스트 시에는 annotatgion 으로 모킹하지 않고, Mock class 사용해서 테스트 케이스를 생성합니다

**Comment by ued123** [comment]
> @ued123
> 
> * spock / ko-test 에서는 참고로 mocking 기반으로 테스트 시에는 annotation 으로 모킹하지 않고, Mock class 사용해서 테스트 케이스를 생성합니다

- 참고 하겠습니다!
